# Generated by Django 5.1 on 2024-08-26 13:49

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdef123456', length=10, max_length=20, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdef123456', length=10, max_length=20, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('Original', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('discount', models.IntegerField(default=0)),
                ('is_accessory', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=100)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('thumbnail_1', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('thumbnail_2', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('thumbnail_3', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartmobicell.category')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisplayProduct',
            fields=[
                ('product_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smartmobicell.product')),
            ],
            bases=('smartmobicell.product',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smartmobicell.product')),
                ('elements', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('added_info', models.CharField(max_length=100)),
            ],
            bases=('smartmobicell.product',),
        ),
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smartmobicell.product')),
                ('description', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
            ],
            bases=('smartmobicell.product',),
        ),
        migrations.CreateModel(
            name='PickOfTheWeek',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smartmobicell.product')),
                ('major_info', models.CharField(max_length=100)),
                ('more_info', models.CharField(max_length=100)),
                ('added_info', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pick of the week',
                'verbose_name_plural': 'Pick of the week',
            },
            bases=('smartmobicell.product',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images')),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
