# Generated by Django 5.0.7 on 2024-08-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmobicell', '0003_order_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='shippingoption',
            field=models.CharField(default='CBD', max_length=100),
            preserve_default=False,
        ),
    ]
