# Generated by Django 5.0.7 on 2024-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmobicell', '0005_remove_orderitems_shippingoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
